dist: bionic
language: node_js
node_js:
  - 13
  - 12
  - 10
services:
  - mysql
stages:
  - test
  - name: npm release
    if: tag IS present
jobs:
  include:
    - stage: npm release
      install: skip
      script: true # skip step with success exit code
      deploy:
        provider: npm
        email: nwoltman@outlook.com
        on:
          tags: true
        api_key:
          secure: uGTx7Dqlu2AMM+uTkoBIOLkEMku5d+Xa1W2ap/pqqYHkY3QoXLMlbIMOWBSt7vxG9Kws+OSbHkl9cGO6db0V96xnXxxa4mhTHroOPocsszU+HmWX0GnQzC2+2IL+gvHCrvltKLKb0q0H9dgIJGCridV2QW38lkHnpavgpeCF+LoBBlTrZubPox408hT1g7olMBeEB8MDV/7N524F8IUDNTALUPZeEIR23bST3H3D0V0+CgwMU2M9CNsjGHV5qOwXBJSt5Y4qTfX8zGmA2XSqu29gripSesVj8a+AU3S8JPtgl1YDj4VCYgalW2E84WE7+3kcrnXvKt4s9uOtnTasy0bOVRR/zc3kS+yWt7avRx66pEC/jPbIZSYxTyrxe8lI1Yxe3+iPBMjYKOeGVl7wIpuiKr4fteBMrUqI7ff+Ku9hJ4aZCjf0m8HrOZp4vl6eGRYAmaFZT0ok72UQXdV8Kb9Bhc5wJ6d3AwWYYG7NItQ1rfdjAyeMtHolBG3YaKVpEB+3wsexU3CsfFugUHIssW+LzE7PHy9vk50XSr5OwMPlVKJwl/woO4pj1We8sahPhPBLAYQy9331FJZf/GD5E9+yuHSnO8FCSfTrjH0gDRhyTINcyOgBDhG3ww2rK8smz5wI64cmo76Mx1YQX5SZ7W/tD/Y/+LENCsB4Wqt8s68=
